import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated, versioned docs (repo-shaped: meta-pantavisor, pantavisor,
// pvr). Autogenerated from the folder structure produced by migrate-docs.js.
//
// Three independent sidebars, each scoped to its own top-level directory, so
// browsing /pantavisor only shows the pantavisor tree and
// /meta-pantavisor only shows the meta-pantavisor tree — instead of
// one shared sidebar showing all three at once.
//
// The meta-pantavisor source tree is structured into two sibling sections,
// getting-started/ and overview/ (labelled "meta-pantavisor" by its
// _category_.json), each with its own navbar link. They get their own
// autogenerated sidebar (scoped to the subdirectory) so the "Getting
// Started" and "meta-pantavisor" navbar links each show only their own
// tree, instead of one combined sidebar with both categories everywhere.
//
// Keys must stay in sync with the SIDEBAR_STUB in scripts/sync-reference.mjs,
// which writes the matching frozen-version sidebar files.
const sidebars: SidebarsConfig = {
  pantavisorSidebar: [{type: 'autogenerated', dirName: 'pantavisor'}],
  metaPantavisorGettingStartedSidebar: [
    {type: 'autogenerated', dirName: 'meta-pantavisor/getting-started'},
  ],
  metaPantavisorOverviewSidebar: [
    {type: 'autogenerated', dirName: 'meta-pantavisor/overview'},
  ],
  pvrSidebar: [{type: 'autogenerated', dirName: 'pvr'}],
};

export default sidebars;
