import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated, versioned docs (repo-shaped: meta-pantavisor, pantavisor,
// pvr). Autogenerated from the folder structure produced by migrate-docs.js.
//
// Three independent sidebars, each scoped to its own top-level directory, so
// browsing /pantavisor only shows the pantavisor tree and
// /meta-pantavisor only shows the meta-pantavisor tree — instead of
// one shared sidebar showing all three at once.
//
// The meta-pantavisor source tree is structured into two sidebar groups:
// getting-started/ and overview/ (which is labelled "meta-pantavisor" by its
// _category_.json). The autogenerated sidebar picks this up naturally, and
// the per-directory _category_.json files control the display labels.
//
// Keys must stay in sync with the SIDEBAR_STUB in scripts/sync-reference.mjs,
// which writes the matching frozen-version sidebar files.
const sidebars: SidebarsConfig = {
  pantavisorSidebar: [{type: 'autogenerated', dirName: 'pantavisor'}],
  metaPantavisorSidebar: [{type: 'autogenerated', dirName: 'meta-pantavisor'}],
  pvrSidebar: [{type: 'autogenerated', dirName: 'pvr'}],
};

export default sidebars;
