import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Curated, versionless documentation: the user-task information architecture,
// authored by hand as Markdown. Fully autogenerated from the folder structure;
// section order is controlled by `sidebar_position` in each section's
// index.md. The generated, versioned reference lives in a separate docs
// instance (see sidebarsReference.ts).
const sidebars: SidebarsConfig = {
  curatedSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'Reference (versioned) →', href: '/reference/pantavisor'},
  ],
};

export default sidebars;
