import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated, versioned reference docs (repo-shaped: meta-pantavisor, pantavisor,
// pvr). Autogenerated from the folder structure produced by migrate-docs.js.
// Key must stay `docsSidebar` to match frozen versioned_sidebars files.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
